commands:
    build:
        executable: pyinstaller
        equalstr: False
        optional:
            name: MyCalc
            additional-hooks-dir: hook_files
            icon: icon.svg
        flags:
            - c
        positional:
            - "--collect-data mycalc"
            - "main.py"
